#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $AUTH_DB_USER WITH PASSWORD '$AUTH_DB_PASSWORD';
	CREATE DATABASE $AUTH_DB;
	GRANT ALL PRIVILEGES ON DATABASE $AUTH_DB TO $AUTH_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AUTH_DB" <<-EOSQL
    GRANT ALL ON SCHEMA public TO $AUTH_DB_USER;
EOSQL


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $CHAT_DB_USER WITH PASSWORD '$CHAT_DB_PASSWORD';
	CREATE DATABASE $CHAT_DB;
	GRANT ALL PRIVILEGES ON DATABASE $CHAT_DB TO $CHAT_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$CHAT_DB" <<-EOSQL
    GRANT ALL ON SCHEMA public TO $CHAT_DB_USER;
EOSQL